[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "zcmds"
description = "Cross platform(ish) productivity commands written in python."
readme = "README.md"
requires-python = ">=3.7"
keywords = ["zcmds"]
license = { text = "BSD 3-Clause License" }
classifiers = ["Programming Language :: Python :: 3"]
dynamic = ["dependencies"]
# Change this with the version number bump.
# Also make the change in zcmds/version.py
version = "1.4.6"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}