[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "zcmds"
description = "Cross platform(ish) productivity commands written in python."
readme = "README.md"
requires-python = ">=3.7"
keywords = ["zcmds"]
license = { text = "BSD 3-Clause License" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "ytclip",
    "pdf2image",
    "ffmpeg-normalize",
    "appdirs",
    "PyQt6==6.3.1",
    "beepy",
    "jsoncomment",
    "zcmds_win32==1.0.1; platform_system=='Windows'",
    "pyserial"
]
# Change this with the version number bump.
# Also make the change in zcmds/version.py
version = "1.3.5"

[project.scripts]
zcmds = "zcmds.cmds.common.zcmds:main"
audnorm = "zcmds.cmds.common.audnorm:main"
comports = "zcmds.cmds.common.comports:main"
diskaudit = "zcmds.cmds.common.diskaudit:main"
findfile = "zcmds.cmds.common.findfile:main"
obs_organize = "zcmds.cmds.common.obs_organize:main"
printenv = "zcmds.cmds.common.printenv:main"
pdf2png = "zcmds.cmds.common.pdf2png:main"
search_and_replace = "zcmds.cmds.common.search_and_replace:main"
search_in_files = "zcmds.cmds.common.search_in_files:main"
sharedir = "zcmds.cmds.common.sharedir:main"
stereo2mono = "zcmds.cmds.common.stereo2mono:main"
vidmute = "zcmds.cmds.common.vidmute:main"
vidinfo = "zcmds.cmds.common.vidinfo:main"
vid2gif = "zcmds.cmds.common.vid2gif:main"
vid2jpg = "zcmds.cmds.common.vid2jpg:main"
vid2mp3 = "zcmds.cmds.common.vid2mp3:main"
vid2mp4 = "zcmds.cmds.common.vid2mp4:main"
vid2webm = "zcmds.cmds.common.vid2webm:main"
vidclip = "zcmds.cmds.common.vidclip:main"
viddur = "zcmds.cmds.common.viddur:main"
vidspeed = "zcmds.cmds.common.vidspeed:main"
vidvol = "zcmds.cmds.common.vidvol:main"
vidshrink = "zcmds.cmds.common.vidshrink:main"
vidmatrix = "zcmds.cmds.common.vidmatrix:main"
vidwebmaster = "zcmds.cmds.common.vidwebmaster:main"
vidhero = "zcmds.cmds.common.vidhero:main"
vidlist = "zcmds.cmds.common.vidlist:main"
test_net_connection = "zcmds.cmds.darwin.test_net_connection:main"
